% vim: set filetype=tex

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{markov}[2022/12/15 A minimalistic LaTeX presentation class]

\LoadClass{beamer}

\beamertemplatenavigationsymbolsempty

\useoutertheme{infolines}
\useinnertheme{circles}

\setbeamercolor{background canvas}
    {bg=brown!25!white}

\setbeamercolor{frametitle}
    {bg=brown!50!black, fg=brown!50!white}

\setbeamercolor{normal text}
    {fg=black}

\setbeamercolor{alerted text}
    {fg=green!50!black}

\setbeamercolor{structure}
    {fg=brown!50!black}

\setbeamercolor{item projected}
    {fg=brown!25!white}

\setbeamercolor{block title}
    {bg=brown!50!black, fg=brown!50!white}

\setbeamercolor{block body}
    {bg=brown!50!white}

\setbeamercolor{block title example}
    {bg=brown!50!black, fg=brown!50!white}

\setbeamercolor{block body example}
    {bg=brown!50!white}
