name:
  Build and release the LaTeX template

on:
  push

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - name:
          Checkout the repo

        uses:
          actions/checkout@v3

      - name:
          Build the template

        uses:
          xu-cheng/latex-action@v2

        with:
          root_file:
            slides.tex

      - name:
          Upload the artifact

        uses:
          actions/upload-artifact@v3

        with:
          name:
            slides-pdf

          path:
            slides.pdf

  release:
    runs-on:
      ubuntu-latest

    needs:
      build

    steps:
      - name:
          Download the artifact

        uses:
          actions/download-artifact@v3

        with:
          name: slides-pdf

      - name:
          Release the template

        uses:
          softprops/action-gh-release@v1

        if:
          startsWith(github.ref, 'refs/tags/')

        with:
          files:
            slides.pdf
